---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: suhlig/grafana-backup-restore-acceptance-test

inputs:
  - name: source

run:
   path: bash
   args:
     - -c
     - |
       service grafana-server start
       cd source
       ginkgo acceptance-tests
